sonar.projectKey=PstEquipmentManagement
sonar.projectName=PstEquipmentManagement
sonar.sourceEncoding=UTF-8
sonar.sources=PstInventory.Core,PstInventory.Infrastructure,PstInventory.WebApp
sonar.language=cs
        